### ISSUE TITLE
variable "about iam_role"

### ISSUE THREAD

**Issue by GarrisonD** [egarbi/terraform-aws-ecs-service#6]
Hi @egarbi! I like your Terraform module, good job! But I have some questions, hope you will be able to answer me soon! 🙂 

1. Could you provide a bit more information about variable "iam_role"?

2. Which kind of policies should this "iam_role" have?

3. Why can't it be created by module?

**Comment by egarbi** [comment]
Hi @GarrisonD, I like you like it :-P
Let me answer your questions:
1. `iam_role` (different from task role) is the role associated with a service. 
The same role and policies associated are shared by all services in the ECS cluster.

2. Typically the policies you associate to such role are related to permissions to register containers under the target_group. Every time that a task is created the ECS agent will automatically register it with the provided target_group
This is the one I'm using at the moment:
```hlc
policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AuthorizeSecurityGroupIngress",
        "ec2:Describe*",
        "elasticloadbalancing:DeregisterTargets",
        "elasticloadbalancing:Describe*",
        "elasticloadbalancing:RegisterTargets"
      ],
      "Resource": "*"
  }
}
```
3. Since the policies within this role need to be set for all services in the ECS cluster is better if you do this externally in a different module.
I didn't publish that module here on GitHub (yet) but it's a module that creates the cluster and the shared policies for instances and services and the shared internal ALB which will be the base for this particular module to run.

Anyway if you think the module can be improved some how just be free to propose it.
Hope it helps.
Thanks
